### ISSUE TITLE
Ready for Packagist??

### ISSUE THREAD

**Issue by kt81** [Codeception/AssertThrows#1]
I updated Codeception/Specify to version 1.0 and it suggested me use this brand new package.
But it seems has not been in Packagist yet.
Is that in progress?

**Comment by Insolita** [comment]
I use it with direct repository in composer, and it works fine for me. Very useful. Hope that it will be released soon, because now Specify not support 'throws' option.

**Comment by DavertMik** [comment]
Sorry, looks like I forgot to publish it :(
Let me fix that

**Comment by DavertMik** [comment]
Finally it's there!

**Comment by kt81** [comment]
Thank you!
