### ISSUE TITLE
assertThrows raise an exception about mismatching messages

### ISSUE THREAD

**Issue by askobara** [Codeception/AssertThrows#4]
There is an example to reproduce:
```php
$this->assertThrows(Exception::class, function () {
    throw new Exception('an exception');
});
```
`exception message '' was expected, but 'an exception' was received`

**Comment by wmathes** [comment]
confirmed. Your fix is valid :) Was about to send a similar PR.

**Comment by ppetpadriew** [comment]
Confirmed. Facing the same problem here.
I will use old version of  `specify` package which does not use this package while this PR is waiting for merge.

**Comment by kagje** [comment]
Accepting this PR would really be appreciated!

**Comment by wmathes** [comment]
@DavertMik please have a look at this.

**Comment by Solomonic** [comment]
Confirmed! Running into the very same issue. Will be fixed with the proposed PR.

**Comment by cyberhck** [comment]
Confirmed, please have a look soon, it's already been quite long when PR is already available.

**Comment by z3niths** [comment]
@DavertMik
@diego-vieira

                      🐞 
                 🐝 🐝 🐝 
           🐝 🐝 🐝 🐝 🐝 
      🐝 🐝 🐝 🐝 🐝 🐝 🐝

**Comment by Lewke** [comment]
Waiting for this PR too...

**Comment by theoc31** [comment]
Confirmed as well! Please can we get this PR merged asap. This is becoming a roadblock in our team flow 😞

**Comment by barthy-koeln** [comment]
In the meantime, I wrapped all the assertion stuff in a `try-catch` block like the following:

```
$this->it(
    "throws an exception",
    function () {
        $this->assertThrows(
            \InvalidArgumentException::class,
            function () {
                try {
                    $this->unitUnderTest->functionUnderTest($param);
                } catch (\InvalidArgumentException $e) {
                     throw new \InvalidArgumentException();
                }
            }
        );
    }
);
```

This just strips the message from the exception. It's ugly and shouldn't be needed, but it does the trick until the PR is merged.

**Comment by ddinchev** [comment]
@DavertMik is there a reason this issue is neglected? If the library is no longer maintained, wouldn't it make sense to say so in the README?
